name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
     
    - name: Build project with Maven
      run: mvn clean package -DskipTests
     
    - name: Upload JAR to server via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "target/products-0.0.1-SNAPSHOT.jar"
        target: "${{ secrets.DEPLOY_DIR }}"
         
    - name: Restart Spring Boot app on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "✅ Starting deployment process..."
          
          # Check if JAR exists
          JAR_PATH="${{ secrets.DEPLOY_DIR }}/target/products-0.0.1-SNAPSHOT.jar"
          if [ ! -f "$JAR_PATH" ]; then
            echo "❌ JAR file not found at: $JAR_PATH"
            exit 1
          fi
          
          echo "✅ JAR file found, restarting service..."
          
          # Restart the systemd service
          sudo systemctl restart spring-app
          sleep 5
          
          # Check service status
          if sudo systemctl is-active --quiet spring-app; then
            echo "✅ Spring Boot application is running!"
            sudo systemctl status spring-app --no-pager -l
          else
            echo "❌ Failed to start Spring Boot application"
            sudo systemctl status spring-app --no-pager -l
            exit 1
          fi